server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
  jpa:
   hibernate:
     ddl-auto: update
   show-sql: true